
export const projects = [
    {
      title: "Portfolio",
      layer: "front-end",
      description: "Portfolio",
      technology: "technology",
      code: "code",
      site: "site",
    },
    {
      title: "Portfolio",
      layer: "front-end",
      description: "Portfolio",
      technology: "technology",
      code: "code",
      site: "site",
    },
    {
      title: "Portfolio",
      layer: "front-end",
      description: "Portfolio",
      technology: "technology",
      code: "code",
      site: "site",
    },
    {
      title: "Portfolio",
      layer: "front-end",
      description: "Portfolio",
      technology: "technology",
      code: "code",
      site: "site",
    },
    {
      title: "Portfolio",
      layer: "front-end",
      description: "Portfolio",
      technology: "technology",
      code: "code",
      site: "site",
    },
    {
      title: "Portfolio",
      layer: "front-end",
      description: "Portfolio",
      technology: "technology",
      code: "code",
      site: "site",
    },
  ]
